find_package(PkgConfig REQUIRED)
pkg_check_modules(CFT_URING REQUIRED IMPORTED_TARGET liburing)
add_executable(cft_persistence_bench persistence/bench.cpp)
sixdb_target(cft_persistence_bench)
target_link_libraries(cft_persistence_bench PRIVATE PkgConfig::CFT_URING)
add_executable(cft_commit_bench commit/bench.cpp)
sixdb_target(cft_commit_bench)
target_link_libraries(cft_commit_bench PRIVATE PkgConfig::CFT_URING)
add_executable(cft_throughput_bench commit/throughput.cpp)
sixdb_target(cft_throughput_bench)
target_link_libraries(cft_throughput_bench PRIVATE PkgConfig::CFT_URING)
