add_library(trie_remapping_core STATIC model.cpp)
sixdb_target(trie_remapping_core)
add_executable(trie_remapping_check check.cpp)
sixdb_target(trie_remapping_check)
target_link_libraries(trie_remapping_check PRIVATE trie_remapping_core)
include(${PROJECT_SOURCE_DIR}/cmake/GoogleBenchmark.cmake)
add_executable(trie_remapping_bench bench.cpp)
sixdb_target(trie_remapping_bench)
target_link_libraries(trie_remapping_bench PRIVATE trie_remapping_core benchmark::benchmark)
