add_library(row_signatures_core STATIC model.cpp)
sixdb_target(row_signatures_core)
add_executable(row_signatures_check check.cpp)
sixdb_target(row_signatures_check)
target_link_libraries(row_signatures_check PRIVATE row_signatures_core)
include(${PROJECT_SOURCE_DIR}/cmake/GoogleBenchmark.cmake)
add_executable(row_signatures_bench bench.cpp)
sixdb_target(row_signatures_bench)
target_link_libraries(row_signatures_bench PRIVATE row_signatures_core benchmark::benchmark)
